#!/usr/bin/env python3

import os
import requests
import json
import sys
import click

from bearer_token import BearerTokenAuth

def fail(s):
    print(s)
    exit(1)

@click.group()
def cli():
    pass

@cli.command()
@click.argument('file')
def key(file):
    with open(file, "r") as f:
        public_key_text = f.read()
    blob = {"name":file, "key":public_key_text}
    response = requests.post(f"{url}/keys", auth=BearerTokenAuth(token), data=json.dumps(blob))
    if response.status_code != 201:
        fail(f"error in request {response.status_code}")
    reply = json.loads(response.text)
    print(reply["id"])

@cli.command()
@click.argument('key')
def cert(key):
    response = requests.get(f"{url}/certs/{key}", auth=BearerTokenAuth(token))
    reply = json.loads(response.text)
    path, extension = os.path.splitext(reply["name"])
    certpath = path + "-cert" + extension
    print(certpath)
    with open(certpath, "w") as f:
        f.write(reply["certificate"])

if __name__ == '__main__':
    url   = os.environ.get('HUSSH_URL', 'http://127.0.0.1:5000')
    token = os.environ.get('HUSSH_TOKEN') or sys.exit('HUSSH_TOKEN missing')
    cli()
