#!/usr/bin/env python3

import os
import logging
import paramiko

from lib.hussh import HUSSH

home = os.path.dirname(os.path.realpath(__file__))

logging.basicConfig()
logfile = os.path.join(home, 'logs', 'hussh.log')
paramiko.util.log_to_file(logfile, level='INFO')

def main():
    hussh = HUSSH(home)
    hussh.listen()

if __name__ == '__main__':
    main()
