#!/usr/bin/env python3

import os
import requests
import json
import click

@click.group()
def cli():
    pass

@cli.command()
@click.argument('file')
def key(file):
    response = requests.post(f"{url}/keys", headers={"token":token}, data="XXX")
    digest = json.loads(response.text)["id"]
    print(digest)

@cli.command()
@click.argument('key')
def cert(key):
    response = requests.get(f"{url}/certs/{key}", headers={"token":token})
    reply = json.loads(response.text)
    print(reply["certificate"])

if __name__ == '__main__':
    url   = os.environ.get('HUSSH_URL', 'http://127.0.0.1:5000')
    token = os.environ['HUSSH_TOKEN']
    cli()
