#!/usr/bin/bash

THIS=$(realpath "$0")
HERE=$(dirname "${THIS}")

DOMAIN="${DOMAIN:-mac.wales}"

HOST_CA="${HERE}/ca/host_ca_key"
USER_CA="${HERE}/ca/user_ca_key"

# --------------------------------------
#

function command_ca {
  mkdir -p "${HERE}/ca" "${HERE}/keys" "${HERE}/hosts" "${HERE}/profiles" "${HERE}/users"

  ssh-keygen -t ecdsa -f ${HOST_CA} \
    -C "Host Certficate Authority for *.${DOMAIN}"
  ssh-keygen -t ed25519 -f ${USER_CA} \
    -C "User Certificate Authority for *.${DOMAIN}"
}

# --------------------------------------
#

COMMAND="$1"
shift
command_${COMMAND} $@
