#!/usr/bin/bash

THIS=$(realpath "$0")
HERE=$(dirname "${THIS}")

DOMAIN="${DOMAIN:-mac.wales}"

HOST_CA="${HERE}/ca/ssh_ca_host_key"
USER_CA="${HERE}/ca/ssh_ca_user_key"

# --------------------------------------

function setup_ca {
  mkdir -p "${HERE}/ca" "${HERE}/keys" "${HERE}/profiles" "${HERE}/logs"

  ssh-keygen -t rsa -f "${HERE}/keys/host.rsa"

  ssh-keygen -t ecdsa -f ${HOST_CA} \
    -C "Host Certficate Authority for *.${DOMAIN}"
  ssh-keygen -t ed25519 -f ${USER_CA} \
    -C "User Certificate Authority for *.${DOMAIN}"
}

# --------------------------------------
#

COMMAND="$1"
shift
setup_${COMMAND} $@
