#!/usr/bin/env python3

import sys
import os
import yaml
import subprocess
from itertools import chain
from pprint import pprint

BASE = os.path.dirname(os.path.realpath(__file__))

s = """
---
key_id: "1000"
serial: 4
principals:
- pete
- root
extensions:
- permit-X11-forwarding
- permit-agent-forwarding
- permit-port-forwarding
- permit-pty
- permit-user-rc
validity: +1d
"""

policy = yaml.safe_load(s)
print(policy)

def sign(policy, keyfile):
    principals = ",".join(policy["principals"])
    args = [
      "ssh-keygen",
      "-s", "ca/user_ca_key",
      "-V", policy["validity"],
      "-I", policy["key_id"],
      "-z", str(policy["serial"]),
      "-n", principals,
      "-O", "clear"
    ]
    options = [ ("-O", f"extension:{option}") for option in policy["extensions"] ]
    args = args + list(chain(*options))
    args.append(keyfile)
    # print(" ".join(args))
    subprocess.call(args)

keyfile = sys.argv[1]
# sign(policy, keyfile)
print(BASE)


#    -V '+24h' \
#   -s ${USER_CA} \
#  -I 'edcba' \
# -z '0004' \
#-n ${NAME} \

# subprocess.call(["ssh-keygen"])
